import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#fff",
  },
  viewButtons: {
    position: "absolute",
    zIndex: 1,
    top: 20,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
  },
  viewButton: {
    padding: 10,
    backgroundColor: "#007AFF",
    borderRadius: 5,
  },
  viewButtonText: {
    color: "#fff",
  },
  tshirtContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  tshirtImage: {
    width: 750,
    height: 750,
    resizeMode: "contain",
  },
  designImageContainer: {
    position: "absolute",
  },
  designImage: {
    width: 150,
    height: 150,
    resizeMode: "contain",
  },
  resizeIcon: {
    position: "absolute",
    top: -10,
    left: -10,
    backgroundColor: "#007AFF",
    borderRadius: 15,
    padding: 5,
  },
  rotateIcon: {
    position: "absolute",
    bottom: -10,
    right: -10,
    backgroundColor: "#007AFF",
    borderRadius: 15,
    padding: 5,
  },
  designText: {
    position: "absolute",
    fontSize: 24,
    color: "#000",
  },
  controls: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 20,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#007AFF",
    padding: 10,
    borderRadius: 5,
  },
  buttonText: {
    color: "#fff",
    marginLeft: 5,
  },
  input: {
    borderColor: "#E5E5EA",
    backgroundColor: "#F2F2F7",
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    flex: 1,
    marginLeft: 10,
  },
  sliderContainer: {
    position: "absolute",
    backgroundColor: "#fff",
    borderRadius: 10,
    bottom: -100,
    left: 20,
    right: 20,
    display: "flex",
  },
  slider: {
    width: "100%",
  },
  designImageContainer: {
    position: "absolute",
  },
  designImage: {
    width: 150,
    height: 150,
    resizeMode: "contain",
  },
  resizeIcon: {
    position: "absolute",
    top: -10,
    left: -10,
    backgroundColor: "#007AFF",
    borderRadius: 15,
    padding: 5,
  },
  rotateIcon: {
    position: "absolute",
    bottom: -10,
    right: -10,
    backgroundColor: "#007AFF",
    borderRadius: 15,
    padding: 5,
  },
  pencilIcon: {
    position: "absolute",
    bottom: -10,
    left: -10,
    backgroundColor: "#007AFF",
    borderRadius: 15,
    padding: 5,
  },
  closeIcon: {
    position: "absolute",
    top: -10,
    right: -10,
    backgroundColor: "#ff0000",
    borderRadius: 15,
    padding: 5,
  },
});
