version: "3.9"

services:
  backend-api-postgres:
    image: postgres:15-alpine

    ports:
      - 5432:5432

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=backend_user
      - POSTGRES_PASSWORD=backend_password

volumes:
  postgres-data:
    name: "backend-api-postgres-data"
