export const dispensaryTestRecord = (id: number = 1) => ({
  id,
  name: `__NAME_${id}__`,
  slug: `__SLUG_${id}__`,
  address: `__ADDRESS_${id}__`,
  city: `__CITY_${id}__`,
  state: `__STATE_${id}__`,
  zip: `__ZIP_${id}__`,
  phone: `__PHONE_${id}__`,
  email: `__EMAIL_${id}__`,
  website: `__WEBSITE_${id}__`,
  licenseInfo: {},
  latitude: Number(40.7128).toFixed(6),
  longitude: Number(-74.006).toFixed(6),
  instagram: `__INSTAGRAM_${id}__`,
  facebook: `__FACEBOOK_${id}__`,
  twitter: `__TWITTER_${id}__`,
  x: `__X_${id}__`,
  amenities: {},
  imageUrl: `__IMAGE_URL_${id}__`,
  priceRange: `__PRICE_RANGE_${id}__`,
  url: `__URL_${id}__`,
  openHours: {},
  bestOfWeedmaps: `__BEST_OF_WEEDMAPS_${id}__`,
  listingType: `__LISTING_TYPE_${id}__`,
  introduction: `__INTRODUCTION_${id}__`,
  about: `__ABOUT_${id}__`,
  announcement: `__ANNOUNCEMENT_${id}__`,
  photos: {},
  menuItemCount: 10,
  menuItemCountCollected: 5,
  reviewCount: 100,
  reviewCountCollected: 50,
  menuItemCountUpdatedAt: new Date('2024-04-18'),
  reviewCountUpdatedAt: new Date('2024-04-18'),
  detailsUpdatedAt: new Date('2024-04-18'),
});
