name: Run Tests and Lint on PR

on:
  pull_request:
    branches:
      - main  # Adjust if needed
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SOCKET_SITE: ${{ vars.NEXT_PUBLIC_SOCKET_SITE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SOCKET_SITE: ${{ vars.NEXT_PUBLIC_SOCKET_SITE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Prettier Check
        run: yarn prettier --check .

  audit:
    name: Security Audit
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SOCKET_SITE: ${{ vars.NEXT_PUBLIC_SOCKET_SITE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Yarn Audit
        run: yarn audit --level high || echo "No high severity vulnerabilities found"

  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SOCKET_SITE: ${{ vars.NEXT_PUBLIC_SOCKET_SITE }}
      NEXT_PUBLIC_BUILDER_API_KEY: ${{ secrets.NEXT_PUBLIC_BUILDER_API_KEY }}
      NEXT_PUBLIC_BUILDER_IO_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_BUILDER_IO_PRIVATE_KEY }}
      NEXT_PUBLIC_ALGOLIA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_CLIENT_ID }}
      NEXT_PUBLIC_ALGOLIA_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_CLIENT_KEY }}
      NEXT_PUBLIC_OPEN_AI_KEY: ${{ secrets.NEXT_PUBLIC_OPEN_AI_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_JWT_SECRET: ${{ secrets.NEXT_PUBLIC_JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_INKSOFT_STORE: ${{ vars.NEXT_PUBLIC_INKSOFT_STORE }}
      NEXT_PUBLIC_SOCKET_SITE: ${{ vars.NEXT_PUBLIC_SOCKET_SITE }}
      NEXT_PUBLIC_BUILDER_API_KEY: ${{ secrets.NEXT_PUBLIC_BUILDER_API_KEY }}
      NEXT_PUBLIC_BUILDER_IO_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_BUILDER_IO_PRIVATE_KEY }}
      NEXT_PUBLIC_ALGOLIA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_CLIENT_ID }}
      NEXT_PUBLIC_ALGOLIA_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_CLIENT_KEY }}
      NEXT_PUBLIC_OPEN_AI_KEY: ${{ secrets.NEXT_PUBLIC_OPEN_AI_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_JWT_SECRET: ${{ secrets.NEXT_PUBLIC_JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        run: yarn web:build

      - name: Run Puppeteer tests
        run: yarn e2e

      - name: Stop Next.js server
        run: pkill -f "next start"
